spring.application.name=marketplace
spring.profiles.active=dev

# DataSource
spring.datasource.url=jdbc:mysql://localhost:3306/digital_marketplace?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&useUnicode=true
spring.datasource.username=root
spring.datasource.password=minhkhuat123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Thymeleaf
spring.thymeleaf.cache=false

# Static resources
spring.web.resources.static-locations=classpath:/static/

# Server
server.port=8386

# Upload dir
app.upload-dir=${user.home}/marketplace-uploads

# VNPay Sandbox
vnpay.tmn-code=DEMO0001
vnpay.hash-secret=DEMOHASHDEMOHASHDEMOHASHDEMO1234
vnpay.payment-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:8386/payment/callback
